// LOCALHOST 
### 
GET http://localhost:8080/players 
### 
GET http://localhost:8080/players/63c60de3dbb283cf7e4f7091

### 
GET http://localhost:8080/players/63c60de3dbb283cf7e4f7092

### 
GET http://localhost:8080/players/63c60de3dbb283cf7e4f7093


### 
GET http://localhost:8080/players/63cf5dfaea69c83250491eea

###
POST http://localhost:8080/players HTTP/1.1
content-type: application/json

{
  "firstName":"Kevin", 
  "lastName":"Durant", 
  "position":"PF/SF", 
  "team":"Nets", 
  "birthday":"09/29/1988",
  "college":"Texas",
  "championships": "2"
}

###
PUT http://localhost:8080/players/63c62263cc63d695f5d3fcb11abd993da0d5acf6bd6ff8f3 HTTP/1.1
content-type: application/json

{
    "firstName":"Kevin",
    "lastName":"Durant",
    "position":"PF/SF",
    "team":"Changes often",
    "birthday":"12/14/1998",
    "college":"Texas",
    "championships": "2"
}

### 
DELETE http://localhost:8080/players/63d1e73d13a91b16751cb735 HTTP/1.1


// PRODUCTION
###
GET https://cse341-lesson5-6.onrender.com/players/

###
POST https://cse341-lesson5-6.onrender.com/players/ HTTP/1.1
content-type: application/json

{
  "firstName":"Kevin", 
  "lastName":"Durant", 
  "position":"PF/SF", 
  "team":"Nets", 
  "birthday":"09/29/1988",
  "college":"Texas",
  "championships":"2"
}

###
PUT https://cse341-lesson5-6.onrender.com/players/63c613ddacf6f4e3e34471ae HTTP/1.1
content-type: application/json

{
    "firstName":"Kevin",
    "lastName":"Durant",
    "position":"PF/SF",
    "team":"Changes often",
    "birthday":"12/14/1998",
    "collge":"Texas",
    "championships":"2"
}

###
DELETE https://cse341-lesson5-6.onrender.com/players/63c613ddacf6f4e3e34471ae HTTP/1.1

### 
GET https://cse341-lesson5-6.onrender.com/players/63c60de3dbb283cf7e4f7091

###
GET https://cse341-lesson5-6.onrender.com/players/63c60de3dbb283cf7e4f7092

### 
GET https://cse341-lesson5-6.onrender.com/players/63c60de3dbb283cf7e4f7093

