// LOCALHOST 
### 
GET http://localhost:8080/contacts 
### 
GET http://localhost:8080/contacts/63b8abb737e2e74a6ad7e9e3

###
POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
  "firstName":"Brandon", 
  "lastName":"Southwick", 
  "email":"brandonemail@test.com", 
  "favoriteColor":"Red", 
  "birthday":"03/04/1998"
}

###
PUT http://localhost:8080/contacts/63b8abb737e2e74a6ad7e9e3 HTTP/1.1
content-type: application/json

{
    "firstName":"Merry",
    "lastName":"Southwick",
    "email":"merryemail1234@test.com",
    "favoriteColor":"Maroon",
    "birthday":"12/14/1998"
}

### 
DELETE http://localhost:8080/contacts/63bcd46ee248c37dbc2c82c2 HTTP/1.1

### 
GET http://localhost:8080/contacts/63b8abb737e2e74a6ad7e9e4

### 
GET http://localhost:8080/contacts/63b8abb737e2e74a6ad7e9e5

// PRODUCTION
###
GET https://cse341-lesson3-vvvz.onrender.com/contacts/ 

###
POST https://cse341-lesson3-vvvz.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Brandon",
    "lastName":"Southwick",
    "email":"brandonsouthwick@test.com",
    "favoriteColor":"Red",
    "birthday":"03/04/1998"
}

###
PUT http://cse341-lesson3-vvvz.onrender.com/contacts/63b8abb737e2e74a6ad7e9e3 HTTP/1.1
content-type: application/json

{
    "firstName":"Merry",
    "lastName":"Southwick",
    "email":"merryemail5@test.com",
    "favoriteColor":"Maroon",
    "birthday":"12/14/1998"
}

###
DELETE http://cse341-lesson3-vvvz.onrender.com/contacts/63bcd94fa881186de51aa443 HTTP/1.1

###
GET http://cse341-lesson3-vvvz.onrender.com/contacts/63b8abb737e2e74a6ad7e9e3

### 
GET http://cse341-lesson3-vvvz.onrender.com/contacts/63b8abb737e2e74a6ad7e9e4

### 
GET http://cse341-lesson3-vvvz.onrender.com/contacts/63b8abb737e2e74a6ad7e9e5
